# -----------------------------------------------------------------------------
# Sync changes to gitlab.com
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.2.0
# -----------------------------------------------------------------------------
name: gitlab-sync

on:
  push:
  delete:
  pull_request:
    types:
      - closed

jobs:
  gitlab-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: uroesch/git-repo-sync@v0.2.6
      with:
        target-url: https://gitlab.com/${{ github.repository }}
        target-username: ${{ github.repository_owner }}
        target-token: ${{ secrets.GITLAB_TOKEN }}
